### ISSUE TITLE
greengrass message bridge appears to fail under load

### ISSUE THREAD

**Issue by wills721** [aws-greengrass/aws-greengrass-mqtt-bridge#171]
**Describe the bug**
MQTT messages sent under heavy load results in loss and failure to publish

**To Reproduce**
Run publishes to topic under load

**Expected behavior**
No failures

**Actual behavior**
In a load test of greengrass v2 ~10000 messages were published to iot topic.  Not all were successful -- about ~200 failed with a message:
greengrass.log:2024-04-05T22:22:54.877Z [ERROR] (pool-3-thread-24) com.aws.greengrass.mqtt.bridge.MessageBridge: Failed to publish. {sourceTopic=thio_bin_uat, source=Pubsub, targetTopic=, target=IotCore, resolvedTargetTopic=thio_bin_uat}

**Environment**
 - OS:  Raspberry Pi
 - JDK version:
 - Nucleus version:
 - MQTT Bridge version:
 - MQTT Broker:

**Additional context**

E.g. what is the impact of the bug?

**Comment by wills721** [comment]
Nucleus version: 2.12.2
MQTT Bridge: 2.3.1
Moquette: 2.3.5

**Comment by MikeDombo** [comment]
Hello,

IoT core is limited to 100 publishes per second. This will be slower with qos 1 messages. Dropping messages is expected with significant load.

To properly send messages from your component, use the publishToIotCore IPC method instead of using the mqtt bridge component to forward from pubsub to iot core. This will provide you with visibility into the success of publishing.

For true reliability, you must implement an application level acknowledgement of you want to ensure that the ultimate destination received the message that you sent.

I hope this helps.

**Comment by wills721** [comment]
Thank you for the quick response!

It seems using the last suggestion you have,  an ACK implementation, is best.  Do you know anywhere I may be able to find some sample code?

Thank you again!
Will

**Comment by MikeDombo** [comment]
Hi Will,
I do not know of an example showing an acknowledgement.

**Comment by wills721** [comment]
No prob.  Thanks again
